AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Emotra Backend API

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        GIN_MODE: release

Resources:
  EmotraAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          # データベース接続情報（環境変数で設定）
          DB_HOST: !Ref DatabaseHost
          DB_PORT: !Ref DatabasePort
          DB_USER: !Ref DatabaseUser
          DB_PASSWORD: !Ref DatabasePassword
          DB_NAME: !Ref DatabaseName

Parameters:
  DatabaseHost:
    Type: String
    Default: localhost
    Description: Database host address
  
  DatabasePort:
    Type: String
    Default: 5432
    Description: Database port
  
  DatabaseUser:
    Type: String
    Default: ginuser
    Description: Database username
  
  DatabasePassword:
    Type: String
    Default: ginpassword
    Description: Database password
  
  DatabaseName:
    Type: String
    Default: emotra
    Description: Database name

Outputs:
  EmotraAPI:
    Description: "API Gateway endpoint URL for Emotra API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  
  EmotraAPIFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt EmotraAPIFunction.Arn 